# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build blog

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 16.5.0
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the blog
      run: npm run build

    - name: Publish to GH pages
      run: |
        cd blog/.vitepress/dist

        git config --global user.email "deploybot@github.com"
        git config --global user.name "DeployBot"

        git add --all
        git commit -m "Deploy $(date)"
        git push -f git@github.com:shybovycha/blog-ssg.github.io.git master:gh-pages
